
--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

select gender, sum(purchase_amount) as revenue
from customer
group by gender

-- This query shows the total money spent by male and female customers separately.
-- SUM(purchase_amount) adds all purchase amounts, and GROUP BY gender divides the data by gender.


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)
 
select customer_id, purchase_amount 
from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer)

-- This query finds customers who:
-- used a discount, and
-- still spent more than or equal to the average spending of all customers.

-- The subquery calculates the average purchase amount.


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

select item_purchased, round(avg(review_rating :: numeric)) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

-- This query finds the top 5 products with the best average customer ratings.

-- AVG(review_rating) calculates average rating
-- ORDER BY ... DESC sorts from highest to lowest
-- LIMIT 5 shows only top 5 products

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

-- This query compares the average spending of customers using:

-- Standard Shipping
-- Express Shipping

-- AVG(purchase_amount) calculates average spending for each shipping type.


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;


select subscription_status, 
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spend,
round(sum(purchase_amount),2) as revenue 
from customer
group by subscription_status
order by revenue,average_spend DESC;

-- This query compares subscribers and non-subscribers based on:

-- total customers
-- average spending
-- total revenue generated

-- It helps check whether subscribed customers spend more money.


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;



--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

select subscription_status, count(customer_id) as repeat_buyers 
from customer
where previous_purchases>5
group  by subscription_status;

-- This query checks whether repeat buyers are subscribed or not.

-- It selects customers with more than 5 previous purchases and counts them based on subscription status.



--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

-- This query shows how much revenue each age group contributes.

-- SUM(purchase_amount) adds total spending
-- GROUP BY age_group separates data by age groups
-- ORDER BY ... DESC shows highest revenue first
